version: '2'

services:
  drone-server:
    image: drone/drone:0.8
    ports:
      - 8000:8000
      #- 9000:9000
    volumes:
      - /var/lib/drone:/var/lib/drone
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_ORGS=lampepfl
      - DRONE_ADMIN=felixmulder,smarter,DarkDimius,NicolasStucki,odersky,liufengyun,OlivierBlanvillain,allanrenucci,gsps,Duhemm
      - DRONE_HOST=172.16.2.90
      - DRONE_GITHUB=true
      - DRONE_GITHUB_MERGE_REF=false
      - DRONE_GITHUB_CLIENT=c9912a5347b37fa7cdae
      - DRONE_GITHUB_SECRET=e4ca86ddc08d56a4855f901a7bbb12ac7659b38b
      - DRONE_SECRET=dronesecret

  drone-agent:
    image: drone/agent:0.8
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_TIMEOUT=10m
      - DRONE_MAX_PROCS=4
      - DRONE_SERVER=drone-server:8000
      - DRONE_SECRET=dronesecret
