version: '2'

services:
  drone-server:
    image: drone/drone:0.8
    ports:
      - 8000:8000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=172.16.2.90
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=c9912a5347b37fa7cdae
      - DRONE_GITHUB_SECRET=e4ca86ddc08d56a4855f901a7bbb12ac7659b38b
      - DRONE_SECRET=test

  drone-agent:
    image: drone/drone:0.8
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=http://172.16.2.90:8000
      - DRONE_SECRET=test